/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import CONEXION.Queries;
import static CONEXION.Queries.guardarPartidaBlackjack;
import static CONEXION.Queries.updateSaldo;
import static CONTROLER.Casino.userActual;
import CONTROLER.GestioLog;
import static CONTROLER.GestioFitxers.tornarMenuClient;
import static CONTROLER.GestioLog.escriureLog;
import CONTROLER.estils;
import MODEL.jocBlackjack;
import java.awt.Graphics;
import javax.swing.JLabel;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author nicod i marti
 */
public class frmBlackjack extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmBlackjack.class.getName());
    private jocBlackjack bj;
    private int totalDealer = 0;
    private int totalJugador = 0;

    /**
     * Creates new form frmBlackjack
     */
    public frmBlackjack() {
        this.setUndecorated(true);
        this.setContentPane(Fondo);
        Fondo.setLayout(null);

        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.setVisible(true);
        estils.border(jPanel1);
        estils.border(jPanel2);
        estils.border(jPanel3);

        saldo();
        escriureLog(userActual + " esta jugant a Blackjack");
        cartaOFF();
        GestioLog.escriureLog(userActual + " esta jugant a Blackjack");

        JPanel2Off();
        JPanel3Off();
        txtApo.putClientProperty("JTextField.placeholderText", "Introdueix Aposta");
        btmJocOff();
        btmTornarOff();
        estils.estilbuto(btmMenu);
        estils.estilbuto(btmIniPartida);
        estils.estilbuto(btmTornar);
        estils.estilbuto(btmCarta);
        estils.estilbuto(btmPlantar);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaldo.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        
        }

    public void saldo() {
        lblSaldo.setText(String.valueOf(userActual.getSaldo()));
    }

    public void totalPartida() {
        lblSum.setText("TOTAL: " + totalJugador);
        lblDealer.setText("DEALER: " + totalDealer);
    }

    private void JPanel2Off() {
        jPanel2.setVisible(false);
    }

    private void JPanel2ON() {
        jPanel2.setVisible(true);
    }

    private void JPanel3Off() {
        jPanel3.setVisible(false);
    }

    private void JPanel3ON() {
        jPanel3.setVisible(true);
    }

    private void ApostaOff() {
        txtApo.setVisible(false);
        btmIniPartida.setVisible(false);
    }

    private void ApostaOn() {
        txtApo.setVisible(true);
        btmIniPartida.setVisible(true);
    }

    private void btmJocOff() {
        btmCarta.setVisible(false);
        btmPlantar.setVisible(false);
    }

    private void btmJocOn() {
        btmCarta.setVisible(true);
        btmPlantar.setVisible(true);
    }

    private void btmTornarOn() {
        btmTornar.setVisible(true);
    }

    private void btmTornarOff() {
        btmTornar.setVisible(false);
    }
    
    JPanel Fondo = new JPanel() {
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            ImageIcon img = new ImageIcon(getClass().getResource("/Images/fons_blackjack.jpg"));
            g.drawImage(img.getImage(), 0, 0, getWidth(), getHeight(), this);
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btmCarta = new javax.swing.JButton();
        btmPlantar = new javax.swing.JButton();
        btmMenu = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        lblCarta2 = new javax.swing.JLabel();
        lblCarta1 = new javax.swing.JLabel();
        lblCarta7 = new javax.swing.JLabel();
        lblCarta3 = new javax.swing.JLabel();
        lblCarta4 = new javax.swing.JLabel();
        lblCarta5 = new javax.swing.JLabel();
        lblCarta6 = new javax.swing.JLabel();
        lblCarta8 = new javax.swing.JLabel();
        lblCarta9 = new javax.swing.JLabel();
        btmIniPartida = new javax.swing.JButton();
        txtApo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lblSum = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        btmTornar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblDealer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(212, 175, 55));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btmCarta.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        btmCarta.setText("➕ CARTA");
        btmCarta.setActionCommand("🖐️CARTA");
        btmCarta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btmCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmCartaActionPerformed(evt);
            }
        });
        getContentPane().add(btmCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 310, 190, 70));

        btmPlantar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        btmPlantar.setText("🖐️PLANTAR");
        btmPlantar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btmPlantar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmPlantarActionPerformed(evt);
            }
        });
        getContentPane().add(btmPlantar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 310, 190, 70));

        btmMenu.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        btmMenu.setText("☰ MENU");
        btmMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btmMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 170, 62));

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCarta2.setText("jLabel1");
        jLayeredPane2.setLayer(lblCarta2, 1);
        jLayeredPane2.add(lblCarta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 160, 233));

        lblCarta1.setText("jLabel1");
        jLayeredPane2.add(lblCarta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 160, 233));

        lblCarta7.setText("jLabel1");
        jLayeredPane2.setLayer(lblCarta7, 6);
        jLayeredPane2.add(lblCarta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 160, 233));

        lblCarta3.setText("jLabel1");
        jLayeredPane2.setLayer(lblCarta3, 2);
        jLayeredPane2.add(lblCarta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 160, 233));

        lblCarta4.setText("jLabel1");
        jLayeredPane2.setLayer(lblCarta4, 3);
        jLayeredPane2.add(lblCarta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 160, 233));

        lblCarta5.setText("jLabel1");
        jLayeredPane2.setLayer(lblCarta5, 4);
        jLayeredPane2.add(lblCarta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 160, 233));

        lblCarta6.setText("jLabel1");
        jLayeredPane2.setLayer(lblCarta6, 5);
        jLayeredPane2.add(lblCarta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 160, 233));

        lblCarta8.setText("jLabel1");
        jLayeredPane2.setLayer(lblCarta8, 8);
        jLayeredPane2.add(lblCarta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, 160, 233));

        lblCarta9.setText("jLabel1");
        jLayeredPane2.setLayer(lblCarta9, 10);
        jLayeredPane2.add(lblCarta9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, 160, 233));

        btmIniPartida.setBackground(new java.awt.Color(0, 0, 0));
        btmIniPartida.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btmIniPartida.setForeground(new java.awt.Color(212, 175, 55));
        btmIniPartida.setText("INICIAR PARTIDA");
        btmIniPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmIniPartidaActionPerformed(evt);
            }
        });
        jLayeredPane2.setLayer(btmIniPartida, javax.swing.JLayeredPane.MODAL_LAYER);
        jLayeredPane2.add(btmIniPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 210, 60));

        txtApo.setBackground(new java.awt.Color(0, 0, 0));
        txtApo.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        txtApo.setForeground(new java.awt.Color(212, 175, 55));
        txtApo.setToolTipText("");
        txtApo.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(212, 175, 55), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        txtApo.setCaretColor(new java.awt.Color(255, 255, 255));
        txtApo.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtApo.setMargin(new java.awt.Insets(10, 6, 2, 6));
        txtApo.setName(""); // NOI18N
        txtApo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApoFocusLost(evt);
            }
        });
        txtApo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApoActionPerformed(evt);
            }
        });
        txtApo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApoKeyTyped(evt);
            }
        });
        jLayeredPane2.setLayer(txtApo, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane2.add(txtApo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 25, 277, 50));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSum.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lblSum.setForeground(new java.awt.Color(212, 175, 55));
        jPanel3.add(lblSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 140, 40));

        jLayeredPane2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 220, 60));

        lblInfo.setBackground(new java.awt.Color(255, 255, 255));
        lblInfo.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(212, 175, 55));
        lblInfo.setToolTipText("");
        lblInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jLayeredPane2.setLayer(lblInfo, 500);
        jLayeredPane2.add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 440, 180));

        getContentPane().add(jLayeredPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 480, 1920, 550));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(212, 175, 55));
        jLabel1.setText("SALDO");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 1, 1));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 370, -1));

        lblSaldo.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        lblSaldo.setForeground(new java.awt.Color(212, 175, 55));
        lblSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaldo.setText("jLabel2");
        lblSaldo.setAlignmentX(0.5F);
        lblSaldo.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 1, 1));
        lblSaldo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 370, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 20, 370, 100));

        btmTornar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        btmTornar.setText("↻TORNAR A JUGAR");
        btmTornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmTornarActionPerformed(evt);
            }
        });
        getContentPane().add(btmTornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 420, 330, 80));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(190, 50));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDealer.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lblDealer.setForeground(new java.awt.Color(212, 175, 55));
        jPanel2.add(lblDealer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 160, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 220, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmCartaActionPerformed
        int carta;
        JPanel3ON();
        if (bj == null) {
            JOptionPane.showMessageDialog(this, "No has iniciat partida");
            return;
        }

        Random random = new Random();
        if (totalJugador >= 18) {
            carta = random.nextInt(11) + 1;
        } else {
            carta = random.nextInt(10) + 2;
        }
        bj.cartaJugador(carta);
        escriureLog(userActual.getNom() + " ha demanat carta: " + carta);
        btmPlantar.setVisible(true);

        System.out.println(bj.toString());
        totalJugador = 0;
        for (int c : bj.getCartesJugador()) {
            totalJugador += c;
        }
        cartaImg();
        totalPartida();
        
        if (totalJugador > 21) {
            lblInfo.setText("T'HAS PASSAT");
            btmJocOff();
            escriureLog(userActual.getNom() + " s'ha passat de 21 amb un total de: " + totalJugador);
            btmTornarOn();
        }

    }//GEN-LAST:event_btmCartaActionPerformed

    private void btmIniPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmIniPartidaActionPerformed
        double aposta = 0.0;
        cartaOFF();
        try {
            aposta = Double.parseDouble(txtApo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El valor introduit no es correcte");
            return;
        }

        if (aposta <= 0) {
            JOptionPane.showMessageDialog(null, "La aposta ha de ser major que 0");
            return;
        }

        if (userActual.getSaldo() < aposta) {
            JOptionPane.showMessageDialog(null, "No tens saldo");
            return;
        }
        userActual.setSaldo(userActual.getSaldo() - aposta);
        Queries.updateSaldo(userActual.getId(), userActual.getSaldo());

        saldo();

        GestioLog.escriureLog(userActual + " ha apostat: " + aposta);

        bj = new jocBlackjack(aposta, "Blackjack");

        ApostaOff();
        btmCarta.setVisible(true);
        //btmPlantar1.setVisible(true);
        System.out.println(bj.toString());

    }//GEN-LAST:event_btmIniPartidaActionPerformed

    private void btmPlantarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmPlantarActionPerformed
        btmJocOff();
        JPanel2ON();
        if (bj == null) {
            JOptionPane.showMessageDialog(null, "No has iniciat partida");
            return;
        }
        escriureLog(userActual.getNom() + " es planta amb un total de: " + totalJugador);
        Random random = new Random();

        while (totalDealer < 18) {
            int carta;

            if (totalDealer >= 17) {
                carta = random.nextInt(6) + 1;

            } else {
                carta = random.nextInt(11) + 1;
            }
            bj.cartaDealer(carta);
            escriureLog("Dealer ha tret carta: " + carta);
            totalDealer = 0;
            for (int c : bj.getCartesDealer()) {
                totalDealer += c;
            }
            System.out.println(bj.toString());

            totalPartida();
        }

        finals();
    }//GEN-LAST:event_btmPlantarActionPerformed

    private void btmMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmMenuActionPerformed
        /* frmMenu s = new frmMenu();
                s.setVisible(true);*/
        tornarMenuClient();
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btmMenuActionPerformed

    private void btmTornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmTornarActionPerformed

        ApostaOn();
        btmTornarOff();
        JPanel2Off();
        JPanel3Off();
        totalDealer = 0;
        totalJugador = 0;
        totalPartida();
        lblInfo.setText("");
        btmJocOff();
        cartaOFF();

// TODO add your handling code here:
    }//GEN-LAST:event_btmTornarActionPerformed

    private void txtApoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApoActionPerformed

    private void txtApoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApoKeyTyped
        char c = evt.getKeyChar();
        String t = txtApo.getText();

        if (!Character.isDigit(c) && c != '.') {
            evt.consume();
        } else if (c == '.' && t.contains(".")) {
            evt.consume();
        } else {
            int i = t.indexOf('.');
            if (i != -1 && t.length() - i > 2) {
                evt.consume();
            }


}    }//GEN-LAST:event_txtApoKeyTyped

    private void txtApoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApoFocusLost

        // TODO add your handling code here:
    }//GEN-LAST:event_txtApoFocusLost

    public void finals() {
        boolean guanyat = false;
        if (totalDealer > 21) {
            lblInfo.setText("HAS GUANYAT");
            guanyat = true;
            btmTornar.setVisible(true);
            userActual.setSaldo(userActual.getSaldo() + bj.getAposta() * 2);
            escriureLog("Final Blackjack: " + userActual.getNom() + " guanya (Dealer s'ha passat). Dealer: " + totalDealer + " - Jugador: " + totalJugador);
        
        } else if (totalJugador > totalDealer) {
            btmTornar.setVisible(true);
            lblInfo.setText("HAS GUANYAT");
            guanyat = true;
            userActual.setSaldo(userActual.getSaldo() + bj.getAposta() * 2);
            escriureLog("Final Blackjack: " + userActual.getNom() + " guanya per punts. Dealer: " + totalDealer + " - Jugador: " + totalJugador);
        
        } else if (totalJugador < totalDealer) {
            btmTornar.setVisible(true);
            lblInfo.setText("Has perdut");
            escriureLog("Final Blackjack: " + userActual.getNom() + " perd per punts. Dealer: " + totalDealer + " - Jugador: " + totalJugador);
        
        } else {
            lblInfo.setText("EMPAT");
            userActual.setSaldo(userActual.getSaldo() + bj.getAposta());
            escriureLog("Final Blackjack: " + userActual.getNom() + " empata. Dealer: " + totalDealer + " - Jugador: " + totalJugador);
        }
        btmTornarOn();
        updateSaldo(userActual.getId(), userActual.getSaldo());
        saldo();

        guardarPartidaBlackjack(userActual.getNom(), totalJugador, totalDealer, guanyat);

    }

    public void cartaOFF() {
        jPanel2.setEnabled(false);
        lblCarta1.setText("");
        lblCarta2.setText("");
        lblCarta3.setText("");
        lblCarta4.setText("");
        lblCarta5.setText("");
        lblCarta6.setText("");
        lblCarta7.setText("");
        lblCarta8.setText("");
        lblCarta9.setText("");
        lblCarta1.setIcon(null);
        lblCarta2.setIcon(null);
        lblCarta3.setIcon(null);
        lblCarta4.setIcon(null);
        lblCarta5.setIcon(null);
        lblCarta6.setIcon(null);
        lblCarta7.setIcon(null);
        lblCarta8.setIcon(null);
        lblCarta9.setIcon(null);

    }

    public void cartaImg() {

        JLabel[] cartes = {
            lblCarta1,
            lblCarta2,
            lblCarta3,
            lblCarta4,
            lblCarta5,
            lblCarta6,
            lblCarta7,
            lblCarta8,
            lblCarta9

        };
        for (int i = 0; i < bj.getCartesJugador().size(); i++) {

            int cart = bj.getCartesJugador().get(i);

            ImageIcon icono = null;

            switch (cart) {
                case 1:
                    icono = new ImageIcon(getClass().getResource("/Images/1.png"));
                    break;
                case 2:
                    icono = new ImageIcon(getClass().getResource("/Images/2.png"));
                    break;
                case 3:
                    icono = new ImageIcon(getClass().getResource("/Images/3.png"));
                    break;
                case 4:
                    icono = new ImageIcon(getClass().getResource("/Images/4.png"));
                    break;
                case 5:
                    icono = new ImageIcon(getClass().getResource("/Images/5.png"));
                    break;
                case 6:
                    icono = new ImageIcon(getClass().getResource("/Images/6.png"));
                    break;
                case 7:
                    icono = new ImageIcon(getClass().getResource("/Images/7.png"));
                    break;
                case 8:
                    icono = new ImageIcon(getClass().getResource("/Images/8.png"));
                    break;
                case 9:
                    icono = new ImageIcon(getClass().getResource("/Images/9.png"));
                    break;
                case 10:
                    icono = new ImageIcon(getClass().getResource("/Images/10.png"));
                    break;
                case 11:
                    icono = new ImageIcon(getClass().getResource("/Images/11.png"));
                    break;
                default:
                    icono = null;
                    break;
            }

            cartes[i].setIcon(icono);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmBlackjack().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmCarta;
    private javax.swing.JButton btmIniPartida;
    private javax.swing.JButton btmMenu;
    private javax.swing.JButton btmPlantar;
    private javax.swing.JButton btmTornar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCarta1;
    private javax.swing.JLabel lblCarta2;
    private javax.swing.JLabel lblCarta3;
    private javax.swing.JLabel lblCarta4;
    private javax.swing.JLabel lblCarta5;
    private javax.swing.JLabel lblCarta6;
    private javax.swing.JLabel lblCarta7;
    private javax.swing.JLabel lblCarta8;
    private javax.swing.JLabel lblCarta9;
    private javax.swing.JLabel lblDealer;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSum;
    private javax.swing.JTextField txtApo;
    // End of variables declaration//GEN-END:variables
}
