/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import CONEXION.Queries;
import static CONEXION.Queries.guardarPartidaBlackjack;
import static CONEXION.Queries.updateSaldo;
import static CONTROLER.Casino.Users;
import static CONTROLER.Casino.userActual;
import CONTROLER.GestioLog;
import static CONTROLER.GestioFitxers.tornarMenuClient;
import static CONTROLER.GestioLog.escriureLog;
import MODEL.jocBlackjack;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author nicod i marti
 */
public class frmBlackjack extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmBlackjack.class.getName());
    private jocBlackjack bj;
    private int totalDealer = 0;
    private int totalJugador = 0;

    /**
     * Creates new form frmBlackjack
     */
    public frmBlackjack() {
        initComponents();
        saldo();
        escriureLog(userActual + " esta jugant a Blackjack");

        btmCarta.setVisible(false);
        btmPlantar1.setVisible(false);
        btmTornar.setVisible(false);

    }

    public void saldo() {
        lblSaldo.setText(String.valueOf(userActual.getSaldo()));
    }

    public void totalPartida() {
        lblSuma.setText("Total: " + totalJugador);
        lblDealer.setText("Total: " + totalDealer);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btmCarta = new javax.swing.JButton();
        btmIniPartida = new javax.swing.JButton();
        btmPlantar1 = new javax.swing.JButton();
        txtApo = new javax.swing.JTextField();
        lblSuma = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblDealer = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        btmMenu = new javax.swing.JButton();
        btmTornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btmCarta.setText("btmCarta");
        btmCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmCartaActionPerformed(evt);
            }
        });

        btmIniPartida.setText("btmIniPartida");
        btmIniPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmIniPartidaActionPerformed(evt);
            }
        });

        btmPlantar1.setText("btmPlantar");
        btmPlantar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmPlantar1ActionPerformed(evt);
            }
        });

        lblInfo.setBackground(new java.awt.Color(255, 255, 255));

        btmMenu.setText("Menu");
        btmMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmMenuActionPerformed(evt);
            }
        });

        btmTornar.setText("tornar a jugar");
        btmTornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmTornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btmIniPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btmPlantar1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtApo, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btmCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(lblSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDealer, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btmMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btmTornar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDealer, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(txtApo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmPlantar1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmIniPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmTornar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmCartaActionPerformed
        int carta;
        if (bj == null) {
            JOptionPane.showMessageDialog(this, "Inicia una partida primer");
            return;
        }

        Random random = new Random();
        if (totalJugador >= 18) {
            carta = random.nextInt(11) + 1;
        } else {
            carta = random.nextInt(10) + 2;
        }
        bj.cartaJugador(carta);
        escriureLog(userActual.getNom() + " ha demanat carta: " + carta);
        btmPlantar1.setVisible(true);

        System.out.println(bj.toString());
        totalJugador = 0;
        for (int c : bj.getCartesJugador()) {
            totalJugador += c;
        }

        totalPartida();

        if (totalJugador > 21) {
            lblInfo.setText("Ets un primo t'has passat");
            escriureLog(userActual.getNom() + " s'ha passat de 21 amb un total de: " + totalJugador);
            btmCarta.setVisible(false);
            btmPlantar1.setVisible(false);
            btmTornar.setVisible(true);
        }

    }//GEN-LAST:event_btmCartaActionPerformed

    private void btmIniPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmIniPartidaActionPerformed
        double aposta;

        try {
            aposta = Double.parseDouble(txtApo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "no");
            return;
        }

        if (aposta <= 0) {
            JOptionPane.showMessageDialog(null, "La aposta ha de ser major que 0");
            return;
        }

        if (userActual.getSaldo() < aposta) {
            JOptionPane.showMessageDialog(null, "No tens saldo");
            return;
        }

        userActual.setSaldo(userActual.getSaldo() - aposta);
        Queries.updateSaldo(userActual.getId(), userActual.getSaldo());

        saldo();

        GestioLog.escriureLog(userActual + " ha apostat: " + aposta);

        bj = new jocBlackjack(aposta, "Blackjack");

        btmIniPartida.setVisible(false);
        txtApo.setVisible(false);
        btmCarta.setVisible(true);
        //btmPlantar1.setVisible(true);
        System.out.println(bj.toString());

    }//GEN-LAST:event_btmIniPartidaActionPerformed

    private void btmPlantar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmPlantar1ActionPerformed
        btmCarta.setEnabled(false);
        btmPlantar1.setEnabled(false);
        if (bj == null) {
            JOptionPane.showMessageDialog(null, "Inicia una partida primero");
            return;
        }
        escriureLog(userActual.getNom() + " es planta amb un total de: " + totalJugador);
        Random random = new Random();

        while (totalDealer < 18) {
            int carta;

            if (totalDealer >= 17) {
                carta = random.nextInt(6) + 1;

            } else {
                carta = random.nextInt(11) + 1;
            }
            bj.cartaDealer(carta);
            escriureLog("Dealer ha tret carta: " + carta);
            totalDealer = 0;
            for (int c : bj.getCartesDealer()) {
                totalDealer += c;
            }
            System.out.println(bj.toString());

            totalPartida();
        }

        finals();
    }//GEN-LAST:event_btmPlantar1ActionPerformed

    private void btmMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmMenuActionPerformed
        /* frmMenu s = new frmMenu();
                s.setVisible(true);*/
        tornarMenuClient();
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btmMenuActionPerformed

    private void btmTornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmTornarActionPerformed
        btmIniPartida.setVisible(true);
        txtApo.setVisible(true);
        btmCarta.setEnabled(true);
        btmPlantar1.setEnabled(true);
        btmTornar.setVisible(false);

        totalDealer = 0;
        totalJugador = 0;
        totalPartida();
        lblInfo.setText("");
        btmCarta.setVisible(false);
        btmPlantar1.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_btmTornarActionPerformed

    public void finals() {
        boolean guanyat = false;
        if (totalDealer > 21) {
            lblInfo.setText("Has guanyat pq el dealer s'ha pasat");
            guanyat = true;
            btmTornar.setVisible(true);
            userActual.setSaldo(userActual.getSaldo() + bj.getAposta() * 2);
            escriureLog("Final Blackjack: " + userActual.getNom() + " guanya (Dealer s'ha passat). Dealer: " + totalDealer + " - Jugador: " + totalJugador);
        
        } else if (totalJugador > totalDealer) {
            btmTornar.setVisible(true);
            lblInfo.setText("Has guanyat");
            guanyat = true;
            userActual.setSaldo(userActual.getSaldo() + bj.getAposta() * 2);
            escriureLog("Final Blackjack: " + userActual.getNom() + " guanya per punts. Dealer: " + totalDealer + " - Jugador: " + totalJugador);
        
        } else if (totalJugador < totalDealer) {
            btmTornar.setVisible(true);
            lblInfo.setText("Has perdut");
            escriureLog("Final Blackjack: " + userActual.getNom() + " perd per punts. Dealer: " + totalDealer + " - Jugador: " + totalJugador);
        
        } else {
            lblInfo.setText("Empat");
            btmTornar.setVisible(true);
            userActual.setSaldo(userActual.getSaldo() + bj.getAposta());
            escriureLog("Final Blackjack: " + userActual.getNom() + " empata. Dealer: " + totalDealer + " - Jugador: " + totalJugador);
        }
        updateSaldo(userActual.getId(), userActual.getSaldo());
        saldo();

        guardarPartidaBlackjack(userActual.getNom(), totalJugador, totalDealer, guanyat);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmBlackjack().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmCarta;
    private javax.swing.JButton btmIniPartida;
    private javax.swing.JButton btmMenu;
    private javax.swing.JButton btmPlantar1;
    private javax.swing.JButton btmTornar;
    private javax.swing.JLabel lblDealer;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSuma;
    private javax.swing.JTextField txtApo;
    // End of variables declaration//GEN-END:variables
}
