/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import static CONTROLER.GestioFitxers.tornarMenuAdmin;
import static CONTROLER.GestioLog.escriureLog;
import static CONTROLER.estils.estilbuto;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Marti Puigvi Serra
 */
public class frmHistorial extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmHistorial.class.getName());

    /**
     * Creates new form frmHistorial
     */
    public frmHistorial() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.setContentPane(Fondo);
        Fondo.setLayout(null);
        Fondo.add(btmBlackjack);
        Fondo.add(btmMenu);
        Fondo.add(btmRuleta);
        Fondo.add(btmTragaperras);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btmBlackjack = new javax.swing.JButton();
        btmRuleta = new javax.swing.JButton();
        btmTragaperras = new javax.swing.JButton();
        btmMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btmBlackjack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/historial_blackjack1 (1).png"))); // NOI18N
        btmBlackjack.setBorderPainted(false);
        btmBlackjack.setContentAreaFilled(false);
        btmBlackjack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmBlackjackActionPerformed(evt);
            }
        });
        getContentPane().add(btmBlackjack, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        btmRuleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/historial_ruleta (1) (1).png"))); // NOI18N
        btmRuleta.setBorderPainted(false);
        btmRuleta.setContentAreaFilled(false);
        btmRuleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmRuletaActionPerformed(evt);
            }
        });
        getContentPane().add(btmRuleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 200, -1, -1));

        btmTragaperras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/historial_tragaperras (1).png"))); // NOI18N
        btmTragaperras.setBorderPainted(false);
        btmTragaperras.setContentAreaFilled(false);
        btmTragaperras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmTragaperrasActionPerformed(evt);
            }
        });
        getContentPane().add(btmTragaperras, new org.netbeans.lib.awtextra.AbsoluteConstraints(915, 200, -1, -1));

        btmMenu.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        btmMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconmenu (1).png"))); // NOI18N
        btmMenu.setContentAreaFilled(false);
        btmMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btmMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 150, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Obre l'historial de Blackjack, tanca la finestra actual i ho registra al
     * log.
     *
     * @param evt
     */
    private void btmBlackjackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmBlackjackActionPerformed
        // TODO add your handling code here:
        frmPartidaBlackjack p = new frmPartidaBlackjack();
        p.setVisible(true);
        this.dispose();
        escriureLog("Admin: Accés a l'historial de partides de Blackjack");
    }//GEN-LAST:event_btmBlackjackActionPerformed

    /**
     * Obre l'historial de Ruleta, tanca la finestra actual i ho registra al
     * log.
     *
     * @param evt
     */
    private void btmRuletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmRuletaActionPerformed
        // TODO add your handling code here:
        frmPartidaRuleta r = new frmPartidaRuleta();
        r.setVisible(true);
        this.dispose();
        escriureLog("Admin: Accés a l'historial de partides de Ruleta");
    }//GEN-LAST:event_btmRuletaActionPerformed

    /**
     * Obre l'historial del Tragaperras, tanca la finestra actual i ho registra
     * al log.
     *
     * @param evt
     */
    private void btmTragaperrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmTragaperrasActionPerformed
        // TODO add your handling code here:
        frmPartidaTragaperras t = new frmPartidaTragaperras();
        t.setVisible(true);
        this.dispose();
        escriureLog("Admin: Accés a l'historial de partides de Tragaperras");
    }//GEN-LAST:event_btmTragaperrasActionPerformed
    
    /**
     * Redirigeix l'administrador de tornada al menú principal i tanca la finestra.
     * @param evt 
     */
    private void btmMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmMenuActionPerformed
        tornarMenuAdmin();
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btmMenuActionPerformed

    JPanel Fondo = new JPanel() {
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            ImageIcon img = new ImageIcon(getClass().getResource("/Images/fondo_historial.png"));
            g.drawImage(img.getImage(), 0, 0, getWidth(), getHeight(), this);
        }
    };

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmHistorial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmBlackjack;
    private javax.swing.JButton btmMenu;
    private javax.swing.JButton btmRuleta;
    private javax.swing.JButton btmTragaperras;
    // End of variables declaration//GEN-END:variables
}
