/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

/**
 *
 * @author Marti Puigvi Serra
 */
public class frmHistorial extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmHistorial.class.getName());

    /**
     * Creates new form frmHistorial
     */
    public frmHistorial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btmHistorialBlackjack = new javax.swing.JButton();
        brmRuleta = new javax.swing.JButton();
        btmTragaperras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btmHistorialBlackjack.setText("BLACK JACK");
        btmHistorialBlackjack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmHistorialBlackjackActionPerformed(evt);
            }
        });

        brmRuleta.setText("RULETA");
        brmRuleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brmRuletaActionPerformed(evt);
            }
        });

        btmTragaperras.setText("TRAGAPERRAS");
        btmTragaperras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmTragaperrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btmHistorialBlackjack)
                .addGap(18, 18, 18)
                .addComponent(brmRuleta)
                .addGap(29, 29, 29)
                .addComponent(btmTragaperras)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmHistorialBlackjack)
                    .addComponent(brmRuleta)
                    .addComponent(btmTragaperras))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmHistorialBlackjackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmHistorialBlackjackActionPerformed
        // TODO add your handling code here:
        frmPartidaBlackjack p = new frmPartidaBlackjack();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btmHistorialBlackjackActionPerformed

    private void brmRuletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brmRuletaActionPerformed
        // TODO add your handling code here:
        frmPartidaRuleta r = new frmPartidaRuleta();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_brmRuletaActionPerformed

    private void btmTragaperrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmTragaperrasActionPerformed
        // TODO add your handling code here:
        frmPartidaTragaperras t = new frmPartidaTragaperras();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btmTragaperrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmHistorial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brmRuleta;
    private javax.swing.JButton btmHistorialBlackjack;
    private javax.swing.JButton btmTragaperras;
    // End of variables declaration//GEN-END:variables
}
