/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import static CONTROLER.Casino.userActual;
import CONTROLER.estils;
import static CONTROLER.estils.estilbuto;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author nicod
 */
public class frmMenu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMenu.class.getName());

    /**
     * Creates new form frmMenu
     */
    public frmMenu(boolean admin) {
        //this.setUndecorated(true);
        initComponents();

        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        this.setContentPane(Fondo);
        Fondo.setLayout(null);
        estilbuto(jButton1);
        estils.border(jPanel2);
        Fondo.add(jButton1);
        Fondo.add(btmBlackJack);
        Fondo.add(btmRuleta);
        Fondo.add(btmTragaPerras);
        Fondo.add(jPanel2);
        Fondo.add(btmConf);
        Fondo.add(btmHistorial);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.CENTER);

        if (admin) {
            btmConf.setVisible(true);
            btmBlackJack.setVisible(false);
            btmRuleta.setVisible(false);
            btmTragaPerras.setVisible(false);
            btmHistorial.setVisible(true);
            jPanel2.setVisible(false);

        } else {
            saldo();
            btmConf.setVisible(false);
            btmHistorial.setVisible(false);

        }

    }
    
    /**
     * Actualitza el text de l'etiqueta de la interfície amb el saldo actual de l'usuari connectat.
     */
    public void saldo() {
        lblSaldo.setText(String.valueOf(userActual.getSaldo()));
    }

    JPanel Fondo = new JPanel() {
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            ImageIcon img = new ImageIcon(getClass().getResource("/Images/menu.png"));
            g.drawImage(img.getImage(), 0, 0, getWidth(), getHeight(), this);
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btmBlackJack = new javax.swing.JButton();
        btmRuleta = new javax.swing.JButton();
        btmTragaPerras = new javax.swing.JButton();
        btmConf = new javax.swing.JButton();
        btmHistorial = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btmBlackJack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blakjack_menu (1).png"))); // NOI18N
        btmBlackJack.setBorder(null);
        btmBlackJack.setBorderPainted(false);
        btmBlackJack.setContentAreaFilled(false);
        btmBlackJack.setMaximumSize(new java.awt.Dimension(586, 347));
        btmBlackJack.setMinimumSize(new java.awt.Dimension(586, 347));
        btmBlackJack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmBlackJackActionPerformed(evt);
            }
        });
        getContentPane().add(btmBlackJack, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 250, 250));

        btmRuleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ruleta_menu (1).png"))); // NOI18N
        btmRuleta.setBorderPainted(false);
        btmRuleta.setContentAreaFilled(false);
        btmRuleta.setPreferredSize(new java.awt.Dimension(400, 400));
        btmRuleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmRuletaActionPerformed(evt);
            }
        });
        getContentPane().add(btmRuleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 250, 250));

        btmTragaPerras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tragaperras_menu (1).png"))); // NOI18N
        btmTragaPerras.setBorderPainted(false);
        btmTragaPerras.setContentAreaFilled(false);
        btmTragaPerras.setMaximumSize(new java.awt.Dimension(586, 347));
        btmTragaPerras.setMinimumSize(new java.awt.Dimension(586, 347));
        btmTragaPerras.setPreferredSize(new java.awt.Dimension(400, 400));
        btmTragaPerras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmTragaPerrasActionPerformed(evt);
            }
        });
        getContentPane().add(btmTragaPerras, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 210, 250, 250));

        btmConf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu_config.png"))); // NOI18N
        btmConf.setToolTipText("");
        btmConf.setBorderPainted(false);
        btmConf.setContentAreaFilled(false);
        btmConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmConfActionPerformed(evt);
            }
        });
        getContentPane().add(btmConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, -1, -1));

        btmHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu_historial.png"))); // NOI18N
        btmHistorial.setBorderPainted(false);
        btmHistorial.setContentAreaFilled(false);
        btmHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmHistorialActionPerformed(evt);
            }
        });
        getContentPane().add(btmHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));

        jButton1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 220, 70));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(212, 175, 55));
        jLabel1.setText("SALDO");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 1, 1));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, -1));

        lblSaldo.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        lblSaldo.setForeground(new java.awt.Color(212, 175, 55));
        lblSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaldo.setText("jLabel2");
        lblSaldo.setAlignmentX(0.5F);
        lblSaldo.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 1, 1));
        lblSaldo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 370, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 20, 370, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Obre la finestra de gestió d'usuaris i tanca la finestra actual del menú.
     * @param evt 
     */
    private void btmConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmConfActionPerformed
        // TODO add your handling code here:
        frmUsers u = new frmUsers();
        u.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btmConfActionPerformed

    /**
     * Obre la finestra de joc de la Ruleta i tanca el menú principal.
     * @param evt 
     */
    private void btmRuletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmRuletaActionPerformed
        // TODO add your handling code here:
        frmRuleta r = new frmRuleta();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btmRuletaActionPerformed

    /**
     * Obre la finestra de joc del Tragaperras i tanca el menú principal.
     * @param evt 
     */
    private void btmTragaPerrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmTragaPerrasActionPerformed
        // TODO add your handling code here:
        frmTragaperras t = new frmTragaperras();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btmTragaPerrasActionPerformed

    /**
     * Obre la finestra de joc del Blackjack i tanca el menú principal.
     * @param evt 
     */
    private void btmBlackJackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmBlackJackActionPerformed
        frmBlackjack f = new frmBlackjack();
        f.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btmBlackJackActionPerformed

    /**
     * Obre la finestra de l'historial de partides i tanca el menú principal.
     * @param evt 
     */
    private void btmHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmHistorialActionPerformed
        // TODO add your handling code here:
        frmHistorial h = new frmHistorial();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btmHistorialActionPerformed
    
    /**
     * Tanca la sessió actual i torna a obrir la finestra d'inici de sessió.
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frmLogIn h = new frmLogIn();
        h.setVisible(true);
        this.dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMenu(false).setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmBlackJack;
    private javax.swing.JButton btmConf;
    private javax.swing.JButton btmHistorial;
    private javax.swing.JButton btmRuleta;
    private javax.swing.JButton btmTragaPerras;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblSaldo;
    // End of variables declaration//GEN-END:variables
}
