/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import static CONTROLER.Casino.userActual;
import CONTROLER.GestioLog;
import java.awt.Graphics;
import javax.swing.JPanel;

/**
 *
 * @author nicod
 */
public class frmMenu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMenu.class.getName());
    private java.awt.Image imatgeFons = new javax.swing.ImageIcon(getClass().getResource("/Images/fons_menu.png")).getImage();

    /**
     * Creates new form frmMenu
     */
    public frmMenu(boolean admin) {
        this.setContentPane(crearPanellFons());
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        if (admin) {
            btmConf.setVisible(true);
            btmBlackJack.setVisible(false);
            btmRuleta.setVisible(false);
            btmTragaPerras.setVisible(false);
            btmHistorial.setVisible(true);

        } else {
            saldo();
            btmConf.setVisible(false);
            btmHistorial.setVisible(false);

        }

    }

    public void saldo() {
        lblSaldo.setText(String.valueOf(userActual.getSaldo()));
    }

    private javax.swing.JPanel crearPanellFons() {
        javax.swing.JPanel panell = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                if (imatgeFons != null) {
                    // El truc és fer servir getWidth() i getHeight() del panell
                    // per estirar la imatge segons la mida de la finestra
                    g.drawImage(imatgeFons, 0, 0, getWidth(), getHeight(), this);
                }
            }
        };
        return panell;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btmBlackJack = new javax.swing.JButton();
        btmRuleta = new javax.swing.JButton();
        btmTragaPerras = new javax.swing.JButton();
        lblSaldo = new javax.swing.JLabel();
        btmConf = new javax.swing.JButton();
        btmHistorial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btmBlackJack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bj_menu.png"))); // NOI18N
        btmBlackJack.setBorder(null);
        btmBlackJack.setBorderPainted(false);
        btmBlackJack.setContentAreaFilled(false);
        btmBlackJack.setMaximumSize(new java.awt.Dimension(586, 347));
        btmBlackJack.setMinimumSize(new java.awt.Dimension(586, 347));
        btmBlackJack.setPreferredSize(new java.awt.Dimension(586, 347));
        btmBlackJack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmBlackJackActionPerformed(evt);
            }
        });

        btmRuleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rule_menu.png"))); // NOI18N
        btmRuleta.setBorderPainted(false);
        btmRuleta.setContentAreaFilled(false);
        btmRuleta.setMinimumSize(new java.awt.Dimension(508, 337));
        btmRuleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmRuletaActionPerformed(evt);
            }
        });

        btmTragaPerras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tp_menu.png"))); // NOI18N
        btmTragaPerras.setBorderPainted(false);
        btmTragaPerras.setContentAreaFilled(false);
        btmTragaPerras.setMaximumSize(new java.awt.Dimension(586, 347));
        btmTragaPerras.setMinimumSize(new java.awt.Dimension(586, 347));
        btmTragaPerras.setPreferredSize(new java.awt.Dimension(586, 347));
        btmTragaPerras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmTragaPerrasActionPerformed(evt);
            }
        });

        btmConf.setText("CONFIG USER");
        btmConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmConfActionPerformed(evt);
            }
        });

        btmHistorial.setText("HISTORIAL PARTIDES");
        btmHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmHistorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(639, 639, 639)
                        .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btmBlackJack, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(476, 476, 476)
                                .addComponent(btmTragaPerras, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(595, 595, 595)
                                .addComponent(btmConf))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(433, 433, 433)
                                .addComponent(btmHistorial))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addComponent(btmRuleta, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblSaldo)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btmBlackJack, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btmTragaPerras, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(btmConf))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(btmHistorial))
                    .addComponent(btmRuleta, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmConfActionPerformed
        // TODO add your handling code here:
        frmUsers u = new frmUsers();
        u.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btmConfActionPerformed

    private void btmRuletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmRuletaActionPerformed
        // TODO add your handling code here:
        frmRuleta r = new frmRuleta();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btmRuletaActionPerformed

    private void btmTragaPerrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmTragaPerrasActionPerformed
        // TODO add your handling code here:
        frmTragaperras t = new frmTragaperras();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btmTragaPerrasActionPerformed

    private void btmHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmHistorialActionPerformed
        // TODO add your handling code here:
        frmHistorial h = new frmHistorial();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btmHistorialActionPerformed

    private void btmBlackJackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmBlackJackActionPerformed
        frmBlackjack f = new frmBlackjack();
        f.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btmBlackJackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMenu(false).setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmBlackJack;
    private javax.swing.JButton btmConf;
    private javax.swing.JButton btmHistorial;
    private javax.swing.JButton btmRuleta;
    private javax.swing.JButton btmTragaPerras;
    private javax.swing.JLabel lblSaldo;
    // End of variables declaration//GEN-END:variables
}
