/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import static CONTROLER.Casino.Admins;
import static CONTROLER.Casino.Users;
import CONTROLER.GestioLog;
import static CONTROLER.GestioLog.escriureLog;
import MODEL.Admin;
import MODEL.Usuari;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author nicod
 */
public class frmSignUp extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmSignUp.class.getName());

    /**
     * Creates new form frmSignUp
     */
    public frmSignUp() {
        initComponents();
        txtName.putClientProperty("JTextField.placeholderText", "Username");
        txtPass.putClientProperty("JTextField.placeholderText", "Password");
        txtAge.putClientProperty("JTextField.placeholderText", "DD-MM-YYYY");
        txtEmail.putClientProperty("JTextField.placeholderText", "Email");

        txtPass.putClientProperty("JTextField.showRevealButton", true);
        GestioLog.escriureLog("Signup iniciat");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btmCancel = new javax.swing.JButton();
        btmSign = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("SIGN UP");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel2.setText("✉️ EMAIL");

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel3.setText("📅 DATE OF BIRTH");

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel4.setText("🔒 PASSWORD");

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel5.setText("👤 USERNAME");

        btmCancel.setForeground(new java.awt.Color(0, 204, 0));
        btmCancel.setText("CANCEL");
        btmCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmCancelActionPerformed(evt);
            }
        });

        btmSign.setBackground(new java.awt.Color(0, 204, 0));
        btmSign.setForeground(new java.awt.Color(255, 255, 255));
        btmSign.setText("SIGN UP");
        btmSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmSignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtAge, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPass, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btmSign)
                        .addGap(18, 18, 18)
                        .addComponent(btmCancel))
                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(169, 169, 169))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmCancel)
                    .addComponent(btmSign))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Valida els camps, comprova que l'usuari/email no existeixi i fa el
     * registre.
     *
     * @param evt
     */
    private void btmSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmSignActionPerformed
        String nom = txtName.getText().toLowerCase();
        String pass = txtPass.getText();
        String email = txtEmail.getText().toLowerCase();
        String age = txtAge.getText();

        escriureLog("Intent de registre per a l'usuari: " + nom);

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");

        if (nom.isEmpty() || pass.isEmpty() || email.isEmpty() || age.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Siusplau, omple tots els camps.", "Error", JOptionPane.ERROR_MESSAGE);
            escriureLog("Error registre: Camps buits detectats.");
            return;
        }

        for (Usuari u : Users) {
            if (u.getNom().equals(nom)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: El nom '" + nom + "' ja està en ús.", "Error", JOptionPane.ERROR_MESSAGE);
                escriureLog("Error registre: El nom '" + nom + "' ja està en ús.");
                return;
            }

            if (u.getEmail().equals(email)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: L'email '" + email + "' ja està en ús.", "Error", JOptionPane.ERROR_MESSAGE);
                escriureLog("Error registre: L'email '" + email + "' ja està en ús.");
                return;
            }

        }

        for (Admin u : Admins) {
            if (u.getNom().equals(nom)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: El nom '" + nom + "' ja està en ús.", "Error", JOptionPane.ERROR_MESSAGE);
                escriureLog("Error registre: Intent de suplentació de nom d'admin: " + nom);
                return;
            }

        }

        try {
            LocalDate data = LocalDate.parse(age, formatter);
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Data incorrecta. Introdueix una data valida", "Error", JOptionPane.ERROR_MESSAGE);
            escriureLog("Error registre: La data es incorrecte.");
            return;
        }

        CONEXION.Queries.signUp(nom, pass, email, age);

        javax.swing.JOptionPane.showMessageDialog(this, "Usuari creat amb exit.");
        this.dispose();
        escriureLog(txtName.getText() + " ha estat registrat al sistema");

        frmLogIn login = new frmLogIn();
        login.setVisible(true);
    }//GEN-LAST:event_btmSignActionPerformed

    /**
     * Cancela el procés i torna a la pantalla de Login.
     *
     * @param evt
     */
    private void btmCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmCancelActionPerformed
        // TODO add your handling code here:
        frmLogIn l = new frmLogIn();
        l.setVisible(true);
        this.dispose();
        escriureLog("L'usuari ha cancel·lat el registre");
    }//GEN-LAST:event_btmCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmSignUp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmCancel;
    private javax.swing.JButton btmSign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
