/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

/**
 *
 * @author Marti Puigvi Serra
 */
public class frmSeleccionarAposta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmSeleccionarAposta.class.getName());

    /**
     * Creates new form frmSeleccionarAposta
     */
    public frmSeleccionarAposta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btm20 = new javax.swing.JButton();
        btm50 = new javax.swing.JButton();
        btm100 = new javax.swing.JButton();
        btm200 = new javax.swing.JButton();
        btm500 = new javax.swing.JButton();
        btm1000 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btm20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fitxa20rb.png"))); // NOI18N
        btm20.setBorderPainted(false);
        btm20.setContentAreaFilled(false);
        btm20.setFocusPainted(false);
        btm20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm20ActionPerformed(evt);
            }
        });

        btm50.setText("50");

        btm100.setText("100");

        btm200.setText("200");

        btm500.setText("500");

        btm1000.setText("1000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btm20, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btm50)
                .addGap(18, 18, 18)
                .addComponent(btm100)
                .addGap(18, 18, 18)
                .addComponent(btm200)
                .addGap(18, 18, 18)
                .addComponent(btm500)
                .addGap(18, 18, 18)
                .addComponent(btm1000)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btm20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btm50)
                            .addComponent(btm100)
                            .addComponent(btm200)
                            .addComponent(btm500)
                            .addComponent(btm1000))))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btm20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btm20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmSeleccionarAposta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm100;
    private javax.swing.JButton btm1000;
    private javax.swing.JButton btm20;
    private javax.swing.JButton btm200;
    private javax.swing.JButton btm50;
    private javax.swing.JButton btm500;
    // End of variables declaration//GEN-END:variables
}
