/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import CONEXION.Queries;
import static CONEXION.Queries.guardarPartidaTragaperras;
import static CONEXION.Queries.historialTragaperras;
import static CONEXION.Queries.updateSaldo;
import static CONTROLER.Casino.userActual;
import static CONTROLER.GestioFitxers.tornarMenuClient;
import CONTROLER.GestioLog;
import static CONTROLER.GestioLog.escriureLog;
import MODEL.jocTrragaperras;
import java.awt.Graphics;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author nicod
 */
public class frmTragaperras extends javax.swing.JFrame {

    private jocTrragaperras tp;
    private Double aposta = 0.0;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmTragaperras.class.getName());

    /**
     * Creates new form frmTragaperras
     */
    public frmTragaperras() {
        this.setUndecorated(true);
                this.setContentPane(Fondo);
        Fondo.setLayout(null);

        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        GestioLog.escriureLog(userActual + " esta jugant al Tragaperras");
        lblInfo.setFont(new java.awt.Font("Segoe UI Emoji", 12, 12));
        lbl2.setFont(new java.awt.Font("Segoe UI Emoji", 24, 24));
        lbl3.setFont(new java.awt.Font("Segoe UI Emoji", 24, 24));
        lbl1.setFont(new java.awt.Font("Segoe UI Emoji", 24, 24));
        btmSeguir.setVisible(false);
        imgOff();
        saldo();
        Aposta();
        //jLabel2.setIcon(null);
    }

    public void saldo() {
        lblSaldo.setText(String.valueOf(userActual.getSaldo()));
    }

    public void Aposta() {
        lblAposta.setText("Aposta actual: " + aposta);
    }

    public void btmApostaOff() {
        btm20.setEnabled(false);
        btm50.setEnabled(false);
        btm100.setEnabled(false);
        btm200.setEnabled(false);
        btm500.setEnabled(false);
    }

    public void btmApostaOn() {
        btm20.setEnabled(true);
        btm50.setEnabled(true);
        btm100.setEnabled(true);
        btm200.setEnabled(true);
        btm500.setEnabled(true);
    }

    public void btmsoff() {
        btmini.setEnabled(false);
        btmSeguir.setEnabled(false);

    }

    public void btmsOn() {
        btmini.setEnabled(true);
        btmSeguir.setEnabled(true);

    }

    private void imgOff() {
        lbl1.setText("");
        lbl2.setText("");
        lbl3.setText("");
        lbl1.setIcon(null);
        lbl2.setIcon(null);
        lbl3.setIcon(null);
    }

        JPanel Fondo = new JPanel() {
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            // Carga la imagen
            ImageIcon img = new ImageIcon(getClass().getResource("/Images/fondo.png"));
            // La dibuja escalada al tamaño del panel
            g.drawImage(img.getImage(), 0, 0, getWidth(), getHeight(), this);
        }
    };
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        btmini = new javax.swing.JButton();
        btm20 = new javax.swing.JButton();
        btm50 = new javax.swing.JButton();
        btm100 = new javax.swing.JButton();
        btm200 = new javax.swing.JButton();
        btm500 = new javax.swing.JButton();
        lblAposta = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblSaldo2 = new javax.swing.JLabel();
        btmSeguir = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        btmMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl1.setBackground(new java.awt.Color(255, 255, 255));
        lbl1.setToolTipText("");
        getContentPane().add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 210, 174));

        lbl2.setToolTipText("");
        getContentPane().add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 480, 210, 174));

        lbl3.setToolTipText("");
        getContentPane().add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 480, 210, 174));

        btmini.setText("btmini");
        btmini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btminiActionPerformed(evt);
            }
        });
        getContentPane().add(btmini, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 80, 100, 40));

        btm20.setText("btm20");
        btm20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm20ActionPerformed(evt);
            }
        });
        getContentPane().add(btm20, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 40, -1, -1));

        btm50.setText("btm50");
        btm50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm50ActionPerformed(evt);
            }
        });
        getContentPane().add(btm50, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        btm100.setText("btm100");
        btm100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm100ActionPerformed(evt);
            }
        });
        getContentPane().add(btm100, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 40, -1, -1));

        btm200.setText("btm200");
        btm200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm200ActionPerformed(evt);
            }
        });
        getContentPane().add(btm200, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 40, -1, -1));

        btm500.setText("btm500");
        btm500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm500ActionPerformed(evt);
            }
        });
        getContentPane().add(btm500, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 40, -1, -1));
        getContentPane().add(lblAposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1145, 123, 147, 23));
        getContentPane().add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 30, 116, 33));
        getContentPane().add(lblSaldo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1145, 82, 80, 23));

        btmSeguir.setText("btmSeguir");
        btmSeguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmSeguirActionPerformed(evt);
            }
        });
        getContentPane().add(btmSeguir, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 82, 115, 40));
        getContentPane().add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(826, 30, 313, 38));

        btmMenu.setText("MENU");
        btmMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btmMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 75, 143, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btminiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btminiActionPerformed
        imgOff();

        btmsoff();
        if (aposta <= 0) {
            JOptionPane.showMessageDialog(null, "La aposta ha de ser major que 0");
            aposta = 0.0;
            Aposta();
            escriureLog(userActual.getNom() + " ha intentat jugar sense apostar.");
            btmsOn();
            return;
        }

        if (userActual.getSaldo() < aposta) {
            escriureLog(userActual.getNom() + " no té saldo suficient per apostar " + aposta);
            JOptionPane.showMessageDialog(null, "No tens saldo");
            aposta = 0.0;
            Aposta();
            btmsOn();
            return;
        }

        escriureLog(userActual.getNom() + " realitza una aposta de " + aposta);
        userActual.setSaldo(userActual.getSaldo() - aposta);
        updateSaldo(userActual.getId(), userActual.getSaldo());

        saldo();
        Aposta();
        btmSeguir.setVisible(true);

        tp = new jocTrragaperras(aposta, "Tragaperras");
        tp.girar();
        System.out.println(tp.toString());
        lblInfo.setText("");

        javax.swing.Timer timer1 = new javax.swing.Timer(2000, e -> {
            // lbl1.setText(tp.getS1());
            iconaImg(lbl1, tp.getS1());
        });
        timer1.setRepeats(false);
        timer1.start();

        javax.swing.Timer timer2 = new javax.swing.Timer(4000, e -> {
            // lbl2.setText(tp.getS2());
            iconaImg(lbl2, tp.getS2());
        });
        timer2.setRepeats(false);
        timer2.start();

        javax.swing.Timer timer3 = new javax.swing.Timer(6000, e -> {
            // lbl3.setText(tp.getS3());
            iconaImg(lbl3, tp.getS3());
            win();
            btmsOn();

        });
        timer3.setRepeats(false);
        timer3.start();
        btmApostaOff();

        // TODO add your handling code here:
    }//GEN-LAST:event_btminiActionPerformed

    private void btm20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm20ActionPerformed
        aposta += 20;
        saldo();
        Aposta();
    }//GEN-LAST:event_btm20ActionPerformed

    private void btm50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm50ActionPerformed
        aposta += 50;
        saldo();
        Aposta();
    }//GEN-LAST:event_btm50ActionPerformed

    private void btm100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm100ActionPerformed
        aposta += 100;
        saldo();
        Aposta();
    }//GEN-LAST:event_btm100ActionPerformed

    private void btm200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm200ActionPerformed
        aposta += 200;
        saldo();
        Aposta();
    }//GEN-LAST:event_btm200ActionPerformed

    private void btm500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm500ActionPerformed
        aposta += 500;
        saldo();
        Aposta();
    }//GEN-LAST:event_btm500ActionPerformed

    private void btmSeguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmSeguirActionPerformed
        imgOff();
        aposta = 0.0;
        btmApostaOn();
        btmini.setEnabled(true);
        btmSeguir.setVisible(false);
        saldo();
        Aposta();
        lblInfo.setText("");

    }//GEN-LAST:event_btmSeguirActionPerformed

    private void btmMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmMenuActionPerformed
        tornarMenuClient();
        this.dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_btmMenuActionPerformed

    private void win() {

        String tipusGuanyador = "Perdut";

        if (tp.getS1().equals(tp.getS2()) && tp.getS2().equals(tp.getS3())) {
            userActual.setSaldo(userActual.getSaldo() + tp.getAposta() * 20);
            String simbolTrio = tp.getS1();
            lblInfo.setText("Has gauanyat per trio " + simbolTrio + " " + aposta * 20);
            tipusGuanyador = "Trio de " + simbolTrio;
            escriureLog(userActual.getNom() + " ha guanyat un TRIO de " + simbolTrio + ". Premi: " + (aposta * 20));
            
        } else if (tp.getS1().equals(tp.getS2()) || tp.getS1().equals(tp.getS3()) || tp.getS2().equals(tp.getS3())) {
            userActual.setSaldo(userActual.getSaldo() + tp.getAposta() * 2);
            String simbolParella = (tp.getS1().equals(tp.getS2()) || tp.getS1().equals(tp.getS3())) ? tp.getS1() : tp.getS2();
            tipusGuanyador = "Parella de " + simbolParella;
            lblInfo.setText("Has gauanyat per parella de " + simbolParella + "  " + aposta * 2);
            escriureLog(userActual.getNom() + " ha guanyat una PARELLA de " + simbolParella + ". Premi: " + (aposta * 2));

        } else {
            lblInfo.setText("Has perdut");
            tipusGuanyador = "Perdut";
            escriureLog(userActual.getNom() + " ha perdut la jugada.");

        }

        guardarPartidaTragaperras(
                userActual.getNom(),
                tp.getS1(),
                tp.getS2(),
                tp.getS3(),
                tipusGuanyador
        );

        historialTragaperras();
        Aposta();
        saldo();
    }

    public void iconaImg(JLabel label, String simbol) {

        ImageIcon icono = null;

        switch (simbol) {
            case "🍒":
                icono = new ImageIcon(getClass().getResource("/Images/cer.png"));
                break;

            case "🍋":
                icono = new ImageIcon(getClass().getResource("/Images/lim.png"));
                break;

            case "⭐":
                icono = new ImageIcon(getClass().getResource("/Images/star.png"));
                break;

            case "💎":
                icono = new ImageIcon(getClass().getResource("/Images/dia.png"));
                break;
        }

        label.setIcon(icono);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmTragaperras().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm100;
    private javax.swing.JButton btm20;
    private javax.swing.JButton btm200;
    private javax.swing.JButton btm50;
    private javax.swing.JButton btm500;
    private javax.swing.JButton btmMenu;
    private javax.swing.JButton btmSeguir;
    private javax.swing.JButton btmini;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lblAposta;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSaldo2;
    // End of variables declaration//GEN-END:variables
}
