/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import static CONEXION.Queries.modUser;
import static CONTROLER.Casino.Users;
import MODEL.Usuari;
import javax.swing.table.DefaultTableModel;
import CONEXION.Queries;
import static CONEXION.Queries.addUser;
import static CONEXION.Queries.delUser;
import static CONEXION.Queries.usuariAaraylist;
import static CONTROLER.GestioFitxers.tornarMenuAdmin;
import static CONTROLER.GestioLog.escriureLog;

/**
 *
 * @author Marti Puigvi Serra
 */
public class frmUsers extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmUsers.class.getName());

    /**
     * Creates new form frmUsers
     */
    public frmUsers() {
        initComponents();
        omplirTaulaUsers();
        lblId.setVisible(false);
        lblNom.setVisible(false);
        lblPass.setVisible(false);
        lblEdat.setVisible(false);
        lblEmail.setVisible(false);
        lblSaldo.setVisible(false);

        txtId.setVisible(false);
        txtNom.setVisible(false);
        txtPass.setVisible(false);
        txtEdat.setVisible(false);
        txtEmail.setVisible(false);
        txtSaldo.setVisible(false);

        btmSave.setVisible(false);

    }

    public void omplirTaulaUsers() {
        tblUsers.clearSelection();
        String col[] = {"ID", "NOM", "CONTRASENYA", "EMAIL", "EDAT", "SALDO"};
        DefaultTableModel tableModel = new DefaultTableModel(col, Users.size());
        tableModel.setRowCount(0);

        for (int i = 0; i < Users.size(); i++) {

            tableModel.insertRow(i, new Object[]{
                Users.get(i).getId(),
                Users.get(i).getNom().toString(),
                Users.get(i).getContrasenya().toString(),
                Users.get(i).getEmail().toString(),
                Users.get(i).getEdat().toString(),
                Users.get(i).getSaldo().toString()

            });
        }
        tblUsers.setModel(tableModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btmAdd = new javax.swing.JButton();
        btmMod = new javax.swing.JButton();
        btmDel = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        lblNom = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        lblEdat = new javax.swing.JLabel();
        txtEdat = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        lblSaldo = new javax.swing.JLabel();
        btmSave = new javax.swing.JButton();
        btmMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("CONF USERS");

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblUsersMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsers);

        btmAdd.setText("ADD");
        btmAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmAddActionPerformed(evt);
            }
        });

        btmMod.setText("MOD");
        btmMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmModActionPerformed(evt);
            }
        });

        btmDel.setText("DEL");
        btmDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmDelActionPerformed(evt);
            }
        });

        txtId.setEditable(false);
        txtId.setToolTipText("");

        lblId.setText("ID");

        lblNom.setText("NOM");

        lblPass.setText("PASSWORD");

        lblEdat.setText("DATA NEIX");

        lblEmail.setText("EMAIL");

        lblSaldo.setText("SALDO");

        btmSave.setText("SAVE");
        btmSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmSaveActionPerformed(evt);
            }
        });

        btmMenu.setText("MENU");
        btmMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(197, 197, 197))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNom))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPass)
                                        .addGap(28, 28, 28)
                                        .addComponent(lblEdat))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtEdat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btmAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btmMod)
                                .addGap(18, 18, 18)
                                .addComponent(btmDel)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btmSave))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btmMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(lblNom)
                    .addComponent(lblPass)
                    .addComponent(lblEdat)
                    .addComponent(lblEmail)
                    .addComponent(lblSaldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btmAdd)
                            .addComponent(btmMod)
                            .addComponent(btmDel))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btmMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmAddActionPerformed
        // TODO add your handling code here:
        escriureLog("Admin: Preparant formulari per afegir nou usuari");

        lblId.setVisible(true);
        lblNom.setVisible(true);
        lblPass.setVisible(true);
        lblEdat.setVisible(true);
        lblEmail.setVisible(true);
        lblSaldo.setVisible(true);

        txtId.setVisible(true);
        txtNom.setVisible(true);
        txtPass.setVisible(true);
        txtEdat.setVisible(true);
        txtEmail.setVisible(true);
        txtSaldo.setVisible(true);

        btmSave.setVisible(true);

        txtId.setText("");
        txtNom.setText("");
        txtPass.setText("");
        txtEdat.setText("");
        txtEmail.setText("");
        txtSaldo.setText("");


    }//GEN-LAST:event_btmAddActionPerformed

    private void btmSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmSaveActionPerformed

        try {
            // 1. Recollim les dades del formulari
            String nom = txtNom.getText();
            String pass = txtPass.getText();
            String email = txtEmail.getText();
            Double saldo = Double.parseDouble(txtSaldo.getText());
            java.time.LocalDate edat = java.time.LocalDate.parse(txtEdat.getText());

            boolean trobat = false;

            if (!txtId.getText().isEmpty()) {
                int idActual = Integer.parseInt(txtId.getText());

                for (int i = 0; i < Users.size(); i++) {
                    if (Users.get(i).getId() == idActual) {
                        Users.get(i).setNom(nom);
                        Users.get(i).setContrasenya(pass);
                        Users.get(i).setEmail(email);
                        Users.get(i).setSaldo(saldo);
                        Users.get(i).setEdat(edat);

                        modUser(idActual, nom, email, pass, edat, saldo);

                        escriureLog("Admin: Usuari modificat (ID: " + idActual + ", Nom: " + nom + ")");

                        trobat = true;
                        break;
                    }
                }
            }

            if (!trobat) {
                addUser(nom, pass, email, edat, saldo);
                escriureLog("Admin: Nou usuari creat directament (Nom: " + nom + ")");
                txtId.setText("");
                txtNom.setText("");
                txtPass.setText("");
                txtEdat.setText("");
                txtEmail.setText("");
                txtSaldo.setText("");
            }

            lblId.setVisible(false);
            lblNom.setVisible(false);
            lblPass.setVisible(false);
            lblEdat.setVisible(false);
            lblEmail.setVisible(false);
            lblSaldo.setVisible(false);

            txtId.setVisible(false);
            txtNom.setVisible(false);
            txtPass.setVisible(false);
            txtEdat.setVisible(false);
            txtEmail.setVisible(false);
            txtSaldo.setVisible(false);

            btmSave.setVisible(false);
            omplirTaulaUsers();

        } catch (Exception e) {
            escriureLog("Admin: Error en guardar usuari (Format de dades incorrecte)");
            javax.swing.JOptionPane.showMessageDialog(null, "Error: Revisa que els nmeros i la data estiguin b.");
        }

    }//GEN-LAST:event_btmSaveActionPerformed

    private void btmDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmDelActionPerformed
        // TODO add your handling code here:
        lblId.setVisible(false);
        lblNom.setVisible(false);
        lblPass.setVisible(false);
        lblEdat.setVisible(false);
        lblEmail.setVisible(false);
        lblSaldo.setVisible(false);

        txtId.setVisible(false);
        txtNom.setVisible(false);
        txtPass.setVisible(false);
        txtEdat.setVisible(false);
        txtEmail.setVisible(false);
        txtSaldo.setVisible(false);

        btmSave.setVisible(false);
        int fila = tblUsers.getSelectedRow();

        if (fila != -1) {
            int id = (int) tblUsers.getValueAt(fila, 0);
            String nomEliminat = tblUsers.getValueAt(fila, 1).toString();

            delUser(id);
            
            escriureLog("Admin: Usuari eliminat (ID: " + id + ", Nom: " + nomEliminat + ")");

            Users.clear();
            usuariAaraylist();

            omplirTaulaUsers();
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Si us plau, selecciona un usuari de la taula.");
        }
    }//GEN-LAST:event_btmDelActionPerformed

    private void btmModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmModActionPerformed
        // TODO add your handling code here:
        lblId.setVisible(true);
        lblNom.setVisible(true);
        lblPass.setVisible(true);
        lblEdat.setVisible(true);
        lblEmail.setVisible(true);
        lblSaldo.setVisible(true);

        txtId.setVisible(true);
        txtNom.setVisible(true);
        txtPass.setVisible(true);
        txtEdat.setVisible(true);
        txtEmail.setVisible(true);
        txtSaldo.setVisible(true);

        btmSave.setVisible(true);
    }//GEN-LAST:event_btmModActionPerformed

    private void tblUsersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsersMousePressed
        // TODO add your handling code here:
        int fila = tblUsers.getSelectedRow();

        if (fila != -1) {
            txtId.setText(tblUsers.getValueAt(fila, 0).toString());
            txtNom.setText(tblUsers.getValueAt(fila, 1).toString());
            txtPass.setText(tblUsers.getValueAt(fila, 2).toString());
            txtEmail.setText(tblUsers.getValueAt(fila, 3).toString());
            txtEdat.setText(tblUsers.getValueAt(fila, 4).toString());
            txtSaldo.setText(tblUsers.getValueAt(fila, 5).toString());

            lblId.setVisible(true);
            lblNom.setVisible(true);
            lblPass.setVisible(true);
            lblEdat.setVisible(true);
            lblEmail.setVisible(true);
            lblSaldo.setVisible(true);

            txtId.setVisible(true);
            txtNom.setVisible(true);
            txtPass.setVisible(true);
            txtEdat.setVisible(true);
            txtEmail.setVisible(true);
            txtSaldo.setVisible(true);

            btmSave.setVisible(true);
        }
    }//GEN-LAST:event_tblUsersMousePressed

    private void btmMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmMenuActionPerformed
        tornarMenuAdmin();
        this.dispose();
        escriureLog("Admin: Tancant gestió d'usuaris i tornant al menú");

// TODO add your handling code here:
    }//GEN-LAST:event_btmMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmUsers().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmAdd;
    private javax.swing.JButton btmDel;
    private javax.swing.JButton btmMenu;
    private javax.swing.JButton btmMod;
    private javax.swing.JButton btmSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEdat;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtEdat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
